version: "3.8"

services:

  service-template-db-test:
    container_name: service-template-db-test
    image: pilot-group-esl/service.template:mysql
    environment:
      MYSQL_ROOT_PASSWORD: "top_secret_test_password"
      MYSQL_DATABASE: "template_test"
      MYSQL_USER: "template_user"
      MYSQL_PASSWORD: "user_secret_test_password"
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  service-template-fpm:
    container_name: service-template-fpm
    image: pilot-group-esl/service.template:fpm
    environment:
      APP_ENV: "test"
      APP_SECRET: "s3cr3tf0rt3st"
      KERNEL_CLASS: App\Kernel

      SYMFONY_DEPRECATIONS_HELPER: 999999
      PANTHER_APP_ENV: "panther"
      PANTHER_ERROR_SCREENSHOT_DIR: "./var/error-screenshots"

      DATABASE_HOST: "service-template-db:3306"
      DATABASE_USERNAME: "template_user"
      DATABASE_PASSWORD: "user_secret_test_password"
      DATABASE_NAME: "template_test"
      DATABASE_URL: "mysql://template_user:user_secret_test_password@service-template-db-test:3306/service-template?serverVersion=8.0"
      DOCTRINE_DEV_MODE: "true"

      PATH: "/var/local/bin:/var/local/src/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    depends_on:
      - service-template-db-test
    command: ["tail", "-f", "/dev/null"]
    stdin_open: true
    tty: true