openapi: 3.0.0
info:
  title: Service Template
  version: 1.0.0
servers:
  - url: https://ADDRR/api/v1
    description: Development environment
  - url: https://tbc.uat/api/v1
    description: Staging environment
  - url: https://tbc.prod/api/v1
    description: Production environment
paths:
  /health:
    get:
      description: |
        Health check endpoint
      responses:
        '200':
          description: |
            Service status OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
              example:
                status: 'OK'
                services:
                  redis: 'Connected'
                  database: 'Connected'
        '503':
          description: |
            Service status Not Available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
              example:
                status: 'Degraded'
                services:
                  redis: 'Connected'
                  database: 'Not connected'


components:

  schemas:
    HealthCheckResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ OK, Degraded ]
          description: >
            Status:
             * `OK` - Connection to all services are up
             * `Degraded` - Connection to one or more services are down
        services:
          type: object
          properties:
            redis:
              type: string
              enum: [ Connected, Not connected ]
              description: >
                Status:
                 * `Connected` - Connection to the service is established
                 * `Not connected` - Connection is down, check logs or contact the system administrator
            database:
              type: string
              enum: [ Connected, Not connected ]
              description: >
                Status:
                 * `Connected` - Connection to the service is established
                 * `Not connected` - Connection is down, check logs or contact the system administrator
      
